version: '3.4'

networks:
  university-accounting-project:
    driver: bridge

services:
  accounting-buildings-app:
    image: docker.io/library/accounting-buildings-app
    depends_on:
      - "accounting-buildings-db"
    container_name: accounting-buildings-app
    ports:
      - "8088:80"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=accounting-buildings-db;Port=5432;Database=accounting_buildings_db; IntegratedSecurity=true;Pooling=true;
    networks:
      - university-accounting-project

  accounting-buildings-db:
    image: postgres:latest
    container_name: accounting-buildings-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting_buildings_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - accounting-buildings-data:/var/lib/postgresql/data
    networks:
      - university-accounting-project
    
volumes:
  accounting-buildings-data: