version: '3.4'

networks:
  university-accounting-project:
    driver: bridge

services:
  accounting-buildings-db:
    image: postgres:latest
    container_name: accounting-buildings-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting_buildings_db
    ports:
      - "5433:5432"
    restart: always
    volumes:
      - accounting-buildings-data:/var/lib/postgresql/data
    networks:
      - university-accounting-project
    
volumes:
  accounting-buildings-data: