version: '3.4'

networks:
  university-accounting-project:
    driver: bridge

services:
  accounting-rooms-app:
    image: docker.io/library/accounting-rooms-app
    depends_on:
      - "accounting-rooms-db"
    container_name: accounting-rooms-app
    ports:
      - "5000:5000"
    environment:
      - ConnectionStrings__DefaultConnection=User ID=postgres;Password=postgres;Server=accounting-rooms-db;Port=5432;Database=accounting_rooms_db; IntegratedSecurity=true;Pooling=true;
    build: 
      context: .
      dockerfile: Dockerfile
    networks:
      - university-accounting-project

  accounting-rooms-db:
    image: postgres:latest
    container_name: accounting-rooms-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=accounting_rooms_db
    ports:
      - "5443:5432"
    restart: always
    volumes:
      - accounting-rooms-data:/var/lib/postgresql/data
    networks:
      - university-accounting-project
    
volumes:
  accounting-rooms-data: